name: Deploy to Azure

on:
  push:
    branches:
      - main

env:
  TF_VERSION: 1.5.6
  TF_ACTION_WORKING_DIR: './terraform'
  TF_STORAGE: ${{ secrets.DEMO_TF_STORAGE_ACCOUNT_NAME }}
  TF_STORAGE_KEY: ${{ secrets.DEMO_TF_STORAGE_KEY }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Run Terraform initialization steps'
      uses: ./.github/actions/terraform-init
      with:
        tf_version: ${{ env.TF_VERSION }}
        tf_working_dir: ${{ env.TF_ACTION_WORKING_DIR }}
        tf_storage: ${{ env.TF_STORAGE }}
        tf_storage_key: ${{ env.TF_STORAGE_KEY }}

    - name: 'Terraform Plan'
      id: plan
      working-directory: ${{ env.TF_ACTION_WORKING_DIR }}
      run: terraform plan -out plan.tfplan -detailed-exitcode

    - name: 'Upload Plan'
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: ${{ env.TF_ACTION_WORKING_DIR }}/plan.tfplan
    
    outputs:
      exitCode: ${{ steps.plan.outputs.exitcode }}

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    # run only if plan was succesful and there are changes
    if: needs.terraform-plan.outputs.exitCode == 2
    # protection policies are used to create a manual approval step
    environment: demo
    steps:
    - name: 'Download Plan'
      uses: actions/download-artifact@v3
      with:
        name: tfplan
        path: ${{ env.TF_ACTION_WORKING_DIR }}

    - name: 'Run Terraform initialization steps'
      uses: ./.github/actions/terraform-init
      with:
        tf_version: ${{ env.TF_VERSION }}
        tf_working_dir: ${{ env.TF_ACTION_WORKING_DIR }}
        tf_storage: ${{ env.TF_STORAGE }}
        tf_storage_key: ${{ env.TF_STORAGE_KEY }}

    - name: 'Terraform Apply'
      working-directory: ${{ env.TF_ACTION_WORKING_DIR }}
      run: terraform apply -auto-approve plan.tfplan
